import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate as runMigrations } from "drizzle-orm/node-postgres/migrator";

/** SQL migrations generated by drizzle-kit (`pnpm --filter @rater/db generate`). */
export const MIGRATIONS_DIR = fileURLToPath(new URL("../migrations", import.meta.url));

/**
 * Any fixed number works; it only has to be the same for every process that migrates.
 * The API and the worker may both migrate on start-up, and the lock makes the second
 * one wait instead of applying the same migration twice.
 */
const MIGRATION_LOCK_ID = 7_310_431;

/** Applies every pending migration in packages/db/migrations. Safe to run concurrently. */
export async function migrate(connectionString: string): Promise<void> {
  // One dedicated connection, because a session-level advisory lock belongs to it.
  const client = new pg.Client({ connectionString });
  await client.connect();
  try {
    await client.query("select pg_advisory_lock($1)", [MIGRATION_LOCK_ID]);
    try {
      await runMigrations(drizzle({ client }), { migrationsFolder: MIGRATIONS_DIR });
    } finally {
      await client.query("select pg_advisory_unlock($1)", [MIGRATION_LOCK_ID]);
    }
  } finally {
    await client.end();
  }
}

function isRunDirectly(): boolean {
  const entry = process.argv[1];
  return (
    entry !== undefined && pathToFileURL(path.resolve(entry)).href === import.meta.url
  );
}

async function main(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("DATABASE_URL is not set");
    process.exit(1);
  }
  await migrate(url);
  console.log("Migrations applied");
}

if (isRunDirectly()) {
  main().catch((error: unknown) => {
    console.error("Migration failed:", error);
    process.exit(1);
  });
}
